name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.0
          
      - run: |
          haxe -version
          haxelib install gm2d
          haxelib install format
          haxelib install nme-toolkit
          haxelib install hxcpp
          
      - name: Build Tool
        run: |
          pwd
          ls
          cd nme/tools
          haxe compile.hxml
        
      - name: Build project
        run: |
          cd project
          haxelib run hxcpp ToolkitBuild.hxml
      
