name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.0
        
      - name: Install haxelibs
        run: |
          haxe -version
          haxelib install gm2d
          haxelib install format
          haxelib install nme-toolkit
          haxelib install hxcpp
          
      - name: Build Tool
        run: |
          pwd
          ls
          cd tools/nme
          haxe compile.hxml
          
      - name: Install SDL libraries
        run: |
          sudo apt-get -y install libasound2-dev libpulse-dev  libaudio-dev libjack-dev libsndio-dev libsamplerate0-dev libx11-dev libxext-dev libxrandr-dev libxcursor-dev libxfixes-dev libxi-dev libxss-dev libwayland-dev libxkbcommon-dev libdrm-dev libgbm-dev libgl1-mesa-dev libgles2-mesa-dev libegl1-mesa-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev
        
      - name: Build Project
        run: |
          cd project
          haxelib run hxcpp ToolkitBuild.xml
          
      - name: Archive Results
        uses: actions/upload-artifact@v3
        with:
          name: linux-64-ndll
          path: ndll/Linux64/nme.dll
          
          

      
