name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.0
      - run: |
          haxe -version
          haxelib install gm2d
          haxelib install format
          haxelib install nme-toolkit
          haxelib install hxcpp
      - run: |
          cd tools/nme
          haxe compile.hxml
      - run: |
          cd project
          haxelib run hxcpp ToolkitBuild.hxml
      
