name: CI
on: [push]

jobs:
 build_matrix:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.0
        
      - name: Install haxelibs
        run: |
          haxe -version
          haxelib install gm2d
          haxelib install format
          haxelib install nme-toolkit
          haxelib install hxcpp
          haxelib dev nme .
          
      - name: Build Tool
        run: |
          cd tools/nme
          haxe compile.hxml

        
      - name: Check XCode
        if: startsWith(matrix.os,'macos')
        run: xcode-select -p
          
      - name: APT Install SDL libraries
        if: startsWith(matrix.os,'ubuntu')
        run: |
          sudo apt-get -y install libasound2-dev libpulse-dev  libaudio-dev libjack-dev libsndio-dev libsamplerate0-dev libx11-dev libxext-dev libxrandr-dev libxcursor-dev libxfixes-dev libxi-dev libxss-dev libwayland-dev libxkbcommon-dev libdrm-dev libgbm-dev libgl1-mesa-dev libgles2-mesa-dev libegl1-mesa-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev
        
      - name: Build Project
        run: |
          cd project
          haxelib run hxcpp ToolkitBuild.xml -DHXCPP_M64
          
      - name: Prep Acadnme
        run: |
           cd acadnme
           haxelib run nme cpp nocompile

      - name: Boot Acadnme
        run: |
           cd samples/AcadnmeBoot
           haxelib run nme cppia installer
           
      - name: Build Acadnme
        run: |
           cd acadnme
           haxelib run nme cpp build -DHXCPP_M64
           
      - name: Setup Emscripten
        if: startsWith(matrix.os,'ubuntu')
        uses: mymindstorm/setup-emsdk@v11

      - name: Build JSPRIME
        if: startsWith(matrix.os,'ubuntu')
        run: |
          cd project
          neko build.n jsprime
        

      - name: Archive Linux Results
        if: startsWith(matrix.os,'ubuntu')
        uses: actions/upload-artifact@v3
        with:
          name: linux-64
          path: |
             ndll/Linux64/nme.ndll
             bin/Linux/Acadnme
             ndll/Emscripten/nme.js
             ndll/Emscripten/nme.js.mem
             ndll/Emscripten/nmeclasses.js
             ndll/Emscripten/preloader.js
             ndll/Emscripten/parsenme.js
             ndll/Emscripten/export_classes.info
             src/cppia/export_classes.info
             
                    
      - name: Archive Windows Results
        if: startsWith(matrix.os,'windows')
        uses: actions/upload-artifact@v3
        with:
          name: windows-64
          path: |
            ndll/Windows64/nme.ndll
            bin/Windows/Acadnme/Acadnme.exe

      - name: Archive Mac Results
        if: startsWith(matrix.os,'macos')
        uses: actions/upload-artifact@v3
        with:
          name: mac-64
          path: |
            ndll/Mac64/nme.ndll
            bin/Mac/Acadnme.app
          

      
